{{- range $name, $svc := .Values.apps }}
{{- if $svc.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.namespaces.apps }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/component: application
    {{- include "smartbank.labels" $ | nindent 4 }}
spec:
  replicas: {{ $svc.replicaCount }}
  selector:
    matchLabels:
      {{- include "smartbank.selectorLabels" (dict "name" $name "instance" $.Release.Name) | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        {{- include "smartbank.selectorLabels" (dict "name" $name "instance" $.Release.Name) | nindent 8 }}
        app.kubernetes.io/part-of: smartbank
      annotations:
        {{- include "smartbank.prometheusAnnotations" (dict "port" $svc.port) | nindent 8 }}
        checksum/config: {{ toJson $svc | sha256sum }}
    spec:
      serviceAccountName: default
      securityContext:
        {{- include "smartbank.podSecurityContext" $ | nindent 8 }}
      affinity:
        {{- include "smartbank.podAntiAffinity" (dict "appName" $name) | nindent 8 }}
      initContainers:
        {{- include "smartbank.waitForInfra" (dict "configServerUrl" $.Values.global.configServerUrl "discoveryUrl" $.Values.global.eurekaUrl) | nindent 8 }}
      containers:
        - name: {{ $name }}
          image: {{ include "smartbank.image" (dict "svc" $svc "global" $.Values.global) }}
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ $svc.port }}
              protocol: TCP
          securityContext:
            {{- include "smartbank.containerSecurityContext" $ | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ $name }}-config
            - secretRef:
                name: {{ $name }}-secret
          resources:
            {{- include "smartbank.resources" $ | nindent 12 }}
          readinessProbe:
            {{- include "smartbank.readinessProbe" (dict "port" $svc.port "global" $.Values.global) | nindent 12 }}
          livenessProbe:
            {{- include "smartbank.livenessProbe" (dict "port" $svc.port "global" $.Values.global) | nindent 12 }}
          volumeMounts:
            {{- include "smartbank.volumeMounts" $ | nindent 12 }}
      volumes:
        {{- include "smartbank.volumes" $ | nindent 8 }}
      terminationGracePeriodSeconds: 30
{{- end }}
{{- end }}