{{- range $name, $svc := .Values.apps }}
{{- if $svc.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-secret
  namespace: {{ $.Values.global.namespaces.apps }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    {{- include "smartbank.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{- /* JWT Secret — most services need it */}}
  {{- if hasKey ($svc.secrets | default dict) "JWT_SECRET" }}
  JWT_SECRET: {{ include "smartbank.secretVal" (dict "svcVal" $svc.secrets.JWT_SECRET "globalVal" $.Values.global.secrets.jwtSecret) | quote }}
  {{- end }}
  {{- /* Database credentials */}}
  {{- if hasKey ($svc.secrets | default dict) "DB_USERNAME" }}
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ $.Values.global.postgresHost }}:5432/{{ $svc.db.name }}"
  SPRING_DATASOURCE_USERNAME: {{ $svc.secrets.DB_USERNAME | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ include "smartbank.secretVal" (dict "svcVal" $svc.secrets.DB_PASSWORD "globalVal" $.Values.global.secrets.postgresPassword) | quote }}
  {{- end }}
  {{- /* Redis password */}}
  {{- if hasKey ($svc.secrets | default dict) "REDIS_PASSWORD" }}
  SPRING_REDIS_PASSWORD: {{ include "smartbank.secretVal" (dict "svcVal" $svc.secrets.REDIS_PASSWORD "globalVal" $.Values.global.secrets.redisPassword) | quote }}
  {{- end }}
  {{- /* Kafka SASL password */}}
  {{- if hasKey ($svc.secrets | default dict) "KAFKA_SASL_PASSWORD" }}
  SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG: {{ include "smartbank.secretVal" (dict "svcVal" $svc.secrets.KAFKA_SASL_PASSWORD "globalVal" $.Values.global.secrets.redisPassword) | quote }}
  {{- end }}
  {{- /* Mail password (notification-service) */}}
  {{- if hasKey ($svc.secrets | default dict) "SPRING_MAIL_PASSWORD" }}
  SPRING_MAIL_PASSWORD: {{ $svc.secrets.SPRING_MAIL_PASSWORD | quote }}
  {{- end }}
  {{- /* SMS API key (notification-service) */}}
  {{- if hasKey ($svc.secrets | default dict) "SMS_API_KEY" }}
  SMS_API_KEY: {{ $svc.secrets.SMS_API_KEY | quote }}
  {{- end }}
{{- end }}
{{- end }}