apiVersion: v1
kind: ConfigMap
metadata:
  name: smartbank-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "smartbank.name" . }}
    {{- include "smartbank.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfilesActive | quote }}
  APP_API_GATEWAY_URL: {{ .Values.config.apiGatewayUrl | quote }}
  SPRING_DATA_REDIS_HOST: {{ .Values.config.redisHost | quote }}
  SPRING_DATA_REDIS_PORT: {{ .Values.config.redisPort | quote }}
  SPRING_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafkaBootstrapServers | quote }}
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: {{ .Values.config.zipkinEndpoint | quote }}
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: {{ .Values.config.healthProbesEnabled | quote }}
  SMTP_HOST: {{ .Values.config.smtp.host | quote }}
  SMTP_PORT: {{ .Values.config.smtp.port | quote }}
  SMTP_AUTH: {{ .Values.config.smtp.auth | quote }}
  SMTP_STARTTLS_ENABLE: {{ .Values.config.smtp.starttlsEnable | quote }}
