apiVersion: v1
kind: Secret
metadata:
  name: smartbank-secret
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "smartbank.name" . }}
    {{- include "smartbank.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secrets.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  CONFIG_SERVER_PASSWORD: {{ .Values.secrets.configServerPassword | quote }}
  EUREKA_PASSWORD: {{ .Values.secrets.eurekaPassword | quote }}
  SMTP_USERNAME: {{ .Values.secrets.smtpUsername | quote }}
  SMTP_PASSWORD: {{ .Values.secrets.smtpPassword | quote }}
  NOTIFICATION_TELEGRAM_ENABLED: {{ .Values.secrets.telegramEnabled | quote }}
  NOTIFICATION_TELEGRAM_BOT_TOKEN: {{ .Values.secrets.telegramBotToken | quote }}
  NOTIFICATION_TELEGRAM_DEFAULT_CHAT_ID: {{ .Values.secrets.telegramDefaultChatId | quote }}
