{{- if .Values.configServer.enabled }}
{{- $svc := .Values.configServer }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: {{ .Values.global.namespaces.infra }}
  labels:
    app.kubernetes.io/name: config-server
    app.kubernetes.io/component: infrastructure
    {{- include "smartbank.labels" . | nindent 4 }}
spec:
  replicas: {{ $svc.replicaCount }}
  selector:
    matchLabels:
      {{- include "smartbank.selectorLabels" (dict "name" "config-server" "instance" .Release.Name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "smartbank.selectorLabels" (dict "name" "config-server" "instance" .Release.Name) | nindent 8 }}
        app.kubernetes.io/part-of: smartbank
      annotations:
        {{- include "smartbank.prometheusAnnotations" (dict "port" $svc.port) | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/infra/config-server/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/infra/config-server/secret.yaml") . | sha256sum }}
    spec:
      serviceAccountName: default
      securityContext:
        {{- include "smartbank.podSecurityContext" . | nindent 8 }}
      affinity:
        {{- include "smartbank.podAntiAffinity" (dict "appName" "config-server") | nindent 8 }}
      containers:
        - name: config-server
          image: {{ include "smartbank.image" (dict "svc" $svc "global" .Values.global) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ $svc.port }}
              protocol: TCP
          securityContext:
            {{- include "smartbank.containerSecurityContext" . | nindent 12 }}
          envFrom:
            - configMapRef:
                name: config-server-config
            - secretRef:
                name: config-server-secret
          resources:
            {{- include "smartbank.resources" . | nindent 12 }}
          readinessProbe:
            {{- include "smartbank.readinessProbe" (dict "port" $svc.port "global" .Values.global) | nindent 12 }}
          livenessProbe:
            {{- include "smartbank.livenessProbe" (dict "port" $svc.port "global" .Values.global) | nindent 12 }}
          volumeMounts:
            {{- include "smartbank.volumeMounts" . | nindent 12 }}
      volumes:
        {{- include "smartbank.volumes" . | nindent 8 }}
      terminationGracePeriodSeconds: 30
{{- end }}
