{{- if .Values.configServer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: config-server-secret
  namespace: {{ .Values.global.namespaces.infra }}
  labels:
    app.kubernetes.io/name: config-server
    {{- include "smartbank.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD: {{ .Values.global.secrets.configServerGitToken | quote }}
  ENCRYPT_KEY: {{ .Values.configServer.encryptKey | quote }}
{{- end }}
