{{- with .Values.global.namespaces }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .infra }}
  labels:
    app.kubernetes.io/part-of: smartbank
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    environment: {{ $.Values.global.environment | default "production" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .apps }}
  labels:
    app.kubernetes.io/part-of: smartbank
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    environment: {{ $.Values.global.environment | default "production" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .data }}
  labels:
    app.kubernetes.io/part-of: smartbank
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    environment: {{ $.Values.global.environment | default "production" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .obs }}
  labels:
    app.kubernetes.io/part-of: smartbank
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    environment: {{ $.Values.global.environment | default "production" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .ingress }}
  labels:
    app.kubernetes.io/part-of: smartbank
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    environment: {{ $.Values.global.environment | default "production" }}
{{- end }}
